stages:
  preprocess:
    cmd: python src/preprocessing/clean_text.py --params params.yaml --raw-dir data/raw --out-dir data/processed
    deps:
      - src/preprocessing/clean_text.py
      - data/raw/wiki.train.raw
      - data/raw/wiki.valid.raw
      - data/raw/wiki.test.raw
    params:
      - preprocessing
    outs:
      - data/processed/train_texts.json
      - data/processed/valid_texts.json
      - data/processed/test_texts.json
  tokenize:
    cmd: python src/preprocessing/tokenizer.py --params params.yaml --in-dir data/processed --out-dir data/processed
    deps:
      - src/preprocessing/tokenizer.py
      - data/processed/train_texts.json
      - data/processed/valid_texts.json
      - data/processed/test_texts.json
    params:
      - tokenizer
    outs:
      - data/processed/tokenizer_word_index.json
      - data/processed/train_sequences.json
      - data/processed/valid_sequences.json
      - data/processed/test_sequences.json
    metrics:
      - data/processed/vocab_stats.json:
          cache: false
  build_sequences:
    cmd: python src/preprocessing/sequences.py --params params.yaml --in-dir data/processed --out-dir data/processed
    deps:
      - src/preprocessing/sequences.py
      - data/processed/train_sequences.json
      - data/processed/valid_sequences.json
      - data/processed/test_sequences.json
    params:
      - sequences
    outs:
      - data/processed/train_X.npy
      - data/processed/train_y.npy
      - data/processed/valid_X.npy
      - data/processed/valid_y.npy
      - data/processed/test_X.npy
      - data/processed/test_y.npy
    metrics:
      - data/processed/sequence_stats.json:
          cache: false
  train:
    cmd: python -m src.train --params params.yaml --data-dir data/processed --model-dir models
    deps:
      - src/train.py
      - src/model/tied_lstm.py
      - data/processed/train_X.npy
      - data/processed/train_y.npy
      - data/processed/valid_X.npy
      - data/processed/valid_y.npy
    params:
      - model
      - train
    outs:
      - models/best_model_tied.keras
  evaluate:
    cmd: python -m src.evaluate --params params.yaml --data-dir data/processed --model-path models/best_model_tied.keras --out metrics.json
    deps:
      - src/evaluate.py
      - src/model/tied_lstm.py
      - models/best_model_tied.keras
      - data/processed/test_X.npy
      - data/processed/test_y.npy
    params:
      - evaluate.batch_size
    metrics:
      - metrics.json:
          cache: false